In [95]:
import trimesh
import numpy as np

In [96]:
def load_mesh(path):

    scene_or_mesh = trimesh.load(path)

    # If file contains a single mesh:
    if isinstance(scene_or_mesh, trimesh.Trimesh):
        mesh = scene_or_mesh

    # If file contains a Scene (most .glb files do)
    else:
        scene = scene_or_mesh

        if not scene.geometry:
            raise ValueError("GLB file contains no mesh geometry.")

        # Extract first mesh from the scene
        mesh = list(scene.geometry.values())[0]
    
    v = mesh.vertices

    # Convert to tuples so numpy arrays become hashable
    as_tuples = [tuple(x) for x in v]

    from collections import Counter
    counts = Counter(as_tuples)

    duplicate_vertices = [v for v, c in counts.items() if c > 1]

    print("Number of unique vertices:", len(counts))
    print("Number of duplicates:", len(v) - len(counts))
    print("Duplicated entries (vertex coordinate):", duplicate_vertices)
    
    print("\nLoaded mesh:", path)
    print("Vertices:", len(mesh.vertices))
    print("Faces:", len(mesh.faces))
    print("Is indexed:", mesh.faces is not None)
    print("Is watertight:", mesh.is_watertight)
    print("Bounds:\n", mesh.bounds)
    print("Vertices:\n", mesh.vertices)

    return mesh


In [106]:
# mesh_path = "/home/student/ss/data/scene_datasets/trial/try/box.glb"
mesh_path = "/home/student/ss/data/scene_datasets/trial/try/box_semantic.ply"

# mesh_path = "/home/student/ss/data/scene_datasets/mp3d/17DRP5sb8fy/17DRP5sb8fy_semantic.ply"
# mesh_path = "/home/student/ss/data/scene_datasets/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb"

load_mesh(mesh_path)

Number of unique vertices: 8
Number of duplicates: 0
Duplicated entries (vertex coordinate): []

Loaded mesh: /home/student/ss/data/scene_datasets/trial/try/box_semantic.ply
Vertices: 8
Faces: 12
Is indexed: True
Is watertight: True
Bounds:
 [[-1. -1. -1.]
 [ 1.  1.  1.]]
Vertices:
 [[ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 1. -1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1. -1.]
 [-1. -1.  1.]
 [-1. -1. -1.]]


<trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [94]:
import trimesh

mesh = trimesh.load("/home/student/ss/data/scene_datasets/trial/try/box_semantic.ply")

print("Vertices:", len(mesh.vertices))
print("Faces:", len(mesh.faces))
print("Is indexed:", mesh.faces is not None)
print(mesh.visual.vertex_colors.shape)


Vertices: 14
Faces: 12
Is indexed: True


AttributeError: 'TextureVisuals' object has no attribute 'vertex_colors'